export interface MockProperty {
  id: string;
  surveyNumber: string;
  district: string;
  taluk: string;
  hobli: string;
  village: string;
  ownerName: string;
  ownerPhone: string;
  areaAcres: number;
  areaGuntas: number;
  propertyType: "Agricultural" | "Non-Agricultural" | "Residential" | "Commercial";
  valuation: number; // in INR
  lat: number;
  lng: number;
  status: "Verified" | "Disputed" | "Pending";
}

export const mockProperties: MockProperty[] = [
  {
    id: "PROP-001",
    surveyNumber: "142/3A",
    district: "Bengaluru Urban",
    taluk: "Yelahanka",
    hobli: "Attur",
    village: "Harohalli",
    ownerName: "Manjunath Gowda",
    ownerPhone: "+91 94481 00213",
    areaAcres: 2,
    areaGuntas: 14,
    propertyType: "Agricultural",
    valuation: 18500000,
    lat: 13.1025,
    lng: 77.5832,
    status: "Verified",
  },
  {
    id: "PROP-002",
    surveyNumber: "88/1",
    district: "Bengaluru Urban",
    taluk: "Kengeri",
    hobli: "Kengeri Hobli",
    village: "Sulikere",
    ownerName: "Lakshmamma R.",
    ownerPhone: "+91 98450 11982",
    areaAcres: 1,
    areaGuntas: 30,
    propertyType: "Agricultural",
    valuation: 12000000,
    lat: 12.9234,
    lng: 77.4612,
    status: "Verified",
  },
  {
    id: "PROP-003",
    surveyNumber: "204/C",
    district: "Mysuru",
    taluk: "Mysuru",
    hobli: "Kasaba",
    village: "Chamundi Hill foothills",
    ownerName: "Vikram R. Urs",
    ownerPhone: "+91 99002 88471",
    areaAcres: 0,
    areaGuntas: 25,
    propertyType: "Residential",
    valuation: 9500000,
    lat: 12.2742,
    lng: 76.6714,
    status: "Verified",
  },
  {
    id: "PROP-004",
    surveyNumber: "45/2",
    district: "Mysuru",
    taluk: "Nanjangud",
    hobli: "Hullahalli",
    village: "Devarasanahalli",
    ownerName: "Basavaraju M.",
    ownerPhone: "+91 94801 32456",
    areaAcres: 4,
    areaGuntas: 8,
    propertyType: "Agricultural",
    valuation: 16000000,
    lat: 12.1245,
    lng: 76.6812,
    status: "Verified",
  },
  {
    id: "PROP-005",
    surveyNumber: "12/4B",
    district: "Belagavi",
    taluk: "Chikodi",
    hobli: "Sadalga",
    village: "Kognoli",
    ownerName: "Devendra Patil",
    ownerPhone: "+91 96112 44781",
    areaAcres: 3,
    areaGuntas: 0,
    propertyType: "Agricultural",
    valuation: 8500000,
    lat: 16.5512,
    lng: 74.4532,
    status: "Verified",
  },
  {
    id: "PROP-006",
    surveyNumber: "301/A",
    district: "Mangaluru (Dakshina Kannada)",
    taluk: "Mangaluru",
    hobli: "Panambur",
    village: "Baikampady",
    ownerName: "Joseph D'Souza",
    ownerPhone: "+91 98860 77123",
    areaAcres: 0,
    areaGuntas: 18,
    propertyType: "Commercial",
    valuation: 32000000,
    lat: 12.9341,
    lng: 74.8315,
    status: "Verified",
  },
  {
    id: "PROP-007",
    surveyNumber: "77/9",
    district: "Mangaluru (Dakshina Kannada)",
    taluk: "Bantwal",
    hobli: "Vittal",
    village: "Kabaka",
    ownerName: "Saraswathi Shenoy",
    ownerPhone: "+91 94498 66251",
    areaAcres: 1,
    areaGuntas: 5,
    propertyType: "Agricultural",
    valuation: 6200000,
    lat: 12.7523,
    lng: 75.1234,
    status: "Disputed",
  },
  {
    id: "PROP-008",
    surveyNumber: "109/2",
    district: "Hubli-Dharwad (Dharwad)",
    taluk: "Hubli",
    hobli: "Hubli Rural",
    village: "Gopankoppa",
    ownerName: "Girish Hublikar",
    ownerPhone: "+91 99805 12567",
    areaAcres: 0,
    areaGuntas: 35,
    propertyType: "Residential",
    valuation: 7800000,
    lat: 15.3725,
    lng: 75.1614,
    status: "Verified",
  },
  {
    id: "PROP-009",
    surveyNumber: "56/3A",
    district: "Hubli-Dharwad (Dharwad)",
    taluk: "Dharwad",
    hobli: "Dharwad Hobli",
    village: "Hebballi",
    ownerName: "Mallikarjun Shinde",
    ownerPhone: "+91 96200 45890",
    areaAcres: 5,
    areaGuntas: 12,
    propertyType: "Agricultural",
    valuation: 14000000,
    lat: 15.4832,
    lng: 75.0312,
    status: "Verified",
  },
  {
    id: "PROP-010",
    surveyNumber: "220/8",
    district: "Bengaluru Urban",
    taluk: "Bengaluru East",
    hobli: "Varthur",
    village: "Gunjur",
    ownerName: "K. R. Venkataswamy",
    ownerPhone: "+91 98440 33910",
    areaAcres: 0,
    areaGuntas: 12,
    propertyType: "Commercial",
    valuation: 28000000,
    lat: 12.9152,
    lng: 77.7425,
    status: "Pending",
  },
];
