export interface MockProperty {
  id: string;
  surveyNumber: string;
  district: string;
  taluk: string;
  hobli: string;
  village: string;
  ownerName: string;
  ownerPhone: string;
  areaAcres: number;
  areaGuntas: number;
  propertyType: "Agricultural" | "Non-Agricultural" | "Residential" | "Commercial" | "Industrial";
  valuation: number; // in INR
  lat: number;
  lng: number;
  status: "Verified" | "Disputed" | "Pending";
  assignedTo?: string; // e.g. "Bibi Ayesha", "R H Adhoni", "Unassigned"
  ownerAddress?: string;
  internalNotes?: string;
  documents?: string[];
  available?: boolean;
}

export const mockProperties: MockProperty[] = [
  {
    id: "PROP-001",
    surveyNumber: "142/3A",
    district: "Bengaluru Urban",
    taluk: "Yelahanka",
    hobli: "Attur",
    village: "Harohalli",
    ownerName: "Manjunath Gowda",
    ownerPhone: "+91 94481 00213",
    areaAcres: 2,
    areaGuntas: 14,
    propertyType: "Agricultural",
    valuation: 18500000,
    lat: 13.1025,
    lng: 77.5832,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "12, Harohalli Main Road, Yelahanka, Bengaluru, Karnataka",
    internalNotes: "Property verification in progress. Title deed clean.",
    documents: ["RTC_Deed_PROP001.pdf", "Survey_Sketch_PROP001.pdf"],
    available: true,
  },
  {
    id: "PROP-002",
    surveyNumber: "88/1",
    district: "Bengaluru Urban",
    taluk: "Kengeri",
    hobli: "Kengeri Hobli",
    village: "Sulikere",
    ownerName: "Lakshmamma R.",
    ownerPhone: "+91 98450 11982",
    areaAcres: 1,
    areaGuntas: 30,
    propertyType: "Agricultural",
    valuation: 12000000,
    lat: 12.9234,
    lng: 77.4612,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "45, Kengeri Hobli, Near Lake Road, Bengaluru, Karnataka",
    internalNotes: "Owner requested loan estimation update. Document scans uploaded.",
    documents: ["RTC_Deed_PROP002.pdf", "Tax_Paid_Receipt_2025.pdf"],
    available: true,
  },
  {
    id: "PROP-003",
    surveyNumber: "204/C",
    district: "Mysuru",
    taluk: "Mysuru",
    hobli: "Kasaba",
    village: "Chamundi Hill foothills",
    ownerName: "Vikram R. Urs",
    ownerPhone: "+91 99002 88471",
    areaAcres: 0,
    areaGuntas: 25,
    propertyType: "Residential",
    valuation: 9500000,
    lat: 12.2742,
    lng: 76.6714,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "78, Foothills, Chamundi Hill Road, Mysuru, Karnataka",
    internalNotes: "Collateral estimation completed. High residential demand.",
    documents: ["RTC_Deed_PROP003.pdf"],
    available: false,
  },
  {
    id: "PROP-004",
    surveyNumber: "45/2",
    district: "Mysuru",
    taluk: "Nanjangud",
    hobli: "Hullahalli",
    village: "Devarasanahalli",
    ownerName: "Basavaraju M.",
    ownerPhone: "+91 94801 32456",
    areaAcres: 4,
    areaGuntas: 8,
    propertyType: "Agricultural",
    valuation: 16000000,
    lat: 12.1245,
    lng: 76.6812,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Sector 3, Devarasanahalli, Nanjangud, Mysuru District, Karnataka",
    internalNotes: "Pending legal clearance check. Survey sketch matches.",
    documents: ["RTC_Deed_PROP004.pdf", "Encumbrance_Cert.pdf"],
    available: true,
  },
  {
    id: "PROP-005",
    surveyNumber: "12/4B",
    district: "Belagavi",
    taluk: "Chikodi",
    hobli: "Sadalga",
    village: "Kognoli",
    ownerName: "Devendra Patil",
    ownerPhone: "+91 96112 44781",
    areaAcres: 3,
    areaGuntas: 0,
    propertyType: "Agricultural",
    valuation: 8500000,
    lat: 16.5512,
    lng: 74.4532,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "120, Sadalga Road, Kognoli, Chikodi Taluk, Belagavi, Karnataka",
    internalNotes: "Approved for refinance. Customer wants to apply for refinance top-up.",
    documents: ["RTC_Deed_PROP005.pdf"],
    available: true,
  },
  {
    id: "PROP-006",
    surveyNumber: "301/A",
    district: "Mangaluru (Dakshina Kannada)",
    taluk: "Mangaluru",
    hobli: "Panambur",
    village: "Baikampady",
    ownerName: "Joseph D'Souza",
    ownerPhone: "+91 98860 77123",
    areaAcres: 0,
    areaGuntas: 18,
    propertyType: "Industrial",
    valuation: 32000000,
    lat: 12.9341,
    lng: 74.8315,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "8-A, Baikampady Industrial Area, Mangaluru, Karnataka",
    internalNotes: "Industrial site. High valuation, verified under corporate loan schema.",
    documents: ["RTC_Deed_PROP006.pdf", "Industrial_Permit.pdf"],
    available: true,
  },
  {
    id: "PROP-007",
    surveyNumber: "77/9",
    district: "Mangaluru (Dakshina Kannada)",
    taluk: "Bantwal",
    hobli: "Vittal",
    village: "Kabaka",
    ownerName: "Saraswathi Shenoy",
    ownerPhone: "+91 94498 66251",
    areaAcres: 1,
    areaGuntas: 5,
    propertyType: "Agricultural",
    valuation: 6200000,
    lat: 12.7523,
    lng: 75.1234,
    status: "Disputed",
    assignedTo: "Unassigned",
    ownerAddress: "99, Vittal Hobli, Bantwal, Dakshina Kannada, Karnataka",
    internalNotes: "Disputed boundary with neighboring plot 77/10. Legal hold active.",
    documents: ["Dispute_Notice.pdf"],
    available: false,
  },
  {
    id: "PROP-008",
    surveyNumber: "109/2",
    district: "Hubli-Dharwad (Dharwad)",
    taluk: "Hubli",
    hobli: "Hubli Rural",
    village: "Gopankoppa",
    ownerName: "Girish Hublikar",
    ownerPhone: "+91 99805 12567",
    areaAcres: 0,
    areaGuntas: 35,
    propertyType: "Residential",
    valuation: 7800000,
    lat: 15.3725,
    lng: 75.1614,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Flat 202, Gopankoppa Rural, Hubli, Dharwad, Karnataka",
    internalNotes: "Residential building under construction. Progress checked by executive.",
    documents: ["RTC_Deed_PROP008.pdf", "Building_Plan_Approval.pdf"],
    available: true,
  },
  {
    id: "PROP-009",
    surveyNumber: "56/3A",
    district: "Hubli-Dharwad (Dharwad)",
    taluk: "Dharwad",
    hobli: "Dharwad Hobli",
    village: "Hebballi",
    ownerName: "Mallikarjun Shinde",
    ownerPhone: "+91 96200 45890",
    areaAcres: 5,
    areaGuntas: 12,
    propertyType: "Agricultural",
    valuation: 14000000,
    lat: 15.4832,
    lng: 75.0312,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "4, Dharwad Hobli, Hebballi, Dharwad, Karnataka",
    internalNotes: "Agricultural land verification done. Soil testing certificate uploaded.",
    documents: ["RTC_Deed_PROP009.pdf"],
    available: true,
  },
  {
    id: "PROP-010",
    surveyNumber: "220/8",
    district: "Bengaluru Urban",
    taluk: "Bengaluru East",
    hobli: "Varthur",
    village: "Gunjur",
    ownerName: "K. R. Venkataswamy",
    ownerPhone: "+91 98440 33910",
    areaAcres: 0,
    areaGuntas: 12,
    propertyType: "Commercial",
    valuation: 28000000,
    lat: 12.9152,
    lng: 77.7425,
    status: "Pending",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Gunjur, Varthur Hobli, Bengaluru East, Karnataka",
    internalNotes: "Commercial plot near IT hub. Highly valued. Ready for joint venture audit.",
    documents: ["RTC_Deed_PROP010.pdf"],
    available: true,
  },
];
