export interface MockProperty {
  id: string;
  surveyNumber: string;
  district: string;
  taluk: string;
  hobli: string;
  village: string;
  ownerName: string;
  ownerPhone: string;
  areaAcres: number;
  areaGuntas: number;
  propertyType: "Agricultural" | "Non-Agricultural" | "Residential" | "Commercial" | "Industrial";
  valuation: number; // in INR
  lat: number;
  lng: number;
  status: "Verified" | "Disputed" | "Pending";
  assignedTo?: string;
  ownerAddress?: string;
  internalNotes?: string;
  documents?: string[];
  available?: boolean;
}

export const mockProperties: MockProperty[] = [
  // ── BENGALURU URBAN ──────────────────────────────────────────────────────────
  {
    id: "PROP-001",
    surveyNumber: "142/3A",
    district: "Bengaluru Urban",
    taluk: "Yelahanka",
    hobli: "Attur",
    village: "Harohalli",
    ownerName: "Manjunath Gowda",
    ownerPhone: "+91 94481 00213",
    areaAcres: 2,
    areaGuntas: 14,
    propertyType: "Agricultural",
    valuation: 18500000,
    lat: 13.1025,
    lng: 77.5832,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "12, Harohalli Main Road, Yelahanka, Bengaluru, Karnataka 560064",
    internalNotes: "Title deed clean. Adjacent to BMRDA layout development zone.",
    documents: ["RTC_Deed_PROP001.pdf", "Survey_Sketch_PROP001.pdf"],
    available: true,
  },
  {
    id: "PROP-002",
    surveyNumber: "88/1",
    district: "Bengaluru Urban",
    taluk: "Kengeri",
    hobli: "Kengeri Hobli",
    village: "Sulikere",
    ownerName: "Lakshmamma R.",
    ownerPhone: "+91 98450 11982",
    areaAcres: 1,
    areaGuntas: 30,
    propertyType: "Agricultural",
    valuation: 12000000,
    lat: 12.9234,
    lng: 77.4612,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "45, Kengeri Hobli, Near Lake Road, Bengaluru, Karnataka 560060",
    internalNotes: "Owner requested loan estimation update. Document scans uploaded.",
    documents: ["RTC_Deed_PROP002.pdf", "Tax_Paid_Receipt_2025.pdf"],
    available: true,
  },
  {
    id: "PROP-010",
    surveyNumber: "220/8",
    district: "Bengaluru Urban",
    taluk: "Bengaluru East",
    hobli: "Varthur",
    village: "Gunjur",
    ownerName: "K. R. Venkataswamy",
    ownerPhone: "+91 98440 33910",
    areaAcres: 0,
    areaGuntas: 12,
    propertyType: "Commercial",
    valuation: 28000000,
    lat: 12.9152,
    lng: 77.7425,
    status: "Pending",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Gunjur, Varthur Hobli, Bengaluru East, Karnataka 560087",
    internalNotes: "Commercial plot near IT hub. Highly valued. Ready for joint venture audit.",
    documents: ["RTC_Deed_PROP010.pdf"],
    available: true,
  },
  {
    id: "PROP-011",
    surveyNumber: "55/2B",
    district: "Bengaluru Urban",
    taluk: "Anekal",
    hobli: "Begur",
    village: "Sarjapur",
    ownerName: "Narayana Swamy",
    ownerPhone: "+91 96865 44120",
    areaAcres: 1,
    areaGuntas: 8,
    propertyType: "Residential",
    valuation: 22000000,
    lat: 12.8731,
    lng: 77.7803,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "Plot 24, Sarjapur Main Road, Anekal Taluk, Bengaluru 562125",
    internalNotes: "Residential layout, clear title. High demand zone near Wipro campus.",
    documents: ["RTC_Deed_PROP011.pdf", "BBMP_Tax_Receipt.pdf"],
    available: true,
  },
  {
    id: "PROP-012",
    surveyNumber: "190/4A",
    district: "Bengaluru Urban",
    taluk: "Devanahalli",
    hobli: "Devanahalli",
    village: "Nehru Nagar",
    ownerName: "Sundarraj B.",
    ownerPhone: "+91 99009 87654",
    areaAcres: 3,
    areaGuntas: 0,
    propertyType: "Non-Agricultural",
    valuation: 41000000,
    lat: 13.2390,
    lng: 77.7133,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "Devanahalli Industrial Area, Near KIADB, Bengaluru Rural 562110",
    internalNotes: "Site near Kempegowda International Airport zone. SEZ eligible.",
    documents: ["RTC_Deed_PROP012.pdf", "NA_Conversion_Order.pdf", "KIADB_NOC.pdf"],
    available: true,
  },
  // ── MYSURU ────────────────────────────────────────────────────────────────────
  {
    id: "PROP-003",
    surveyNumber: "204/C",
    district: "Mysuru",
    taluk: "Mysuru",
    hobli: "Kasaba",
    village: "Chamundi Hill foothills",
    ownerName: "Vikram R. Urs",
    ownerPhone: "+91 99002 88471",
    areaAcres: 0,
    areaGuntas: 25,
    propertyType: "Residential",
    valuation: 9500000,
    lat: 12.2742,
    lng: 76.6714,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "78, Foothills, Chamundi Hill Road, Mysuru, Karnataka 570010",
    internalNotes: "Collateral estimation completed. High residential demand.",
    documents: ["RTC_Deed_PROP003.pdf"],
    available: false,
  },
  {
    id: "PROP-004",
    surveyNumber: "45/2",
    district: "Mysuru",
    taluk: "Nanjangud",
    hobli: "Hullahalli",
    village: "Devarasanahalli",
    ownerName: "Basavaraju M.",
    ownerPhone: "+91 94801 32456",
    areaAcres: 4,
    areaGuntas: 8,
    propertyType: "Agricultural",
    valuation: 16000000,
    lat: 12.1245,
    lng: 76.6812,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Sector 3, Devarasanahalli, Nanjangud, Mysuru District, Karnataka 571301",
    internalNotes: "Pending legal clearance check. Survey sketch matches.",
    documents: ["RTC_Deed_PROP004.pdf", "Encumbrance_Cert.pdf"],
    available: true,
  },
  {
    id: "PROP-013",
    surveyNumber: "310/1",
    district: "Mysuru",
    taluk: "Hunsur",
    hobli: "Hunsur Hobli",
    village: "Bettadapura",
    ownerName: "Prema T. Narayanaswamy",
    ownerPhone: "+91 94483 12340",
    areaAcres: 6,
    areaGuntas: 18,
    propertyType: "Agricultural",
    valuation: 9800000,
    lat: 12.2975,
    lng: 76.2852,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "Bettadapura, Hunsur Taluk, Mysuru District, Karnataka 571105",
    internalNotes: "Irrigated paddy land. Kaveri river tributary adjacent. Good for farm loan.",
    documents: ["RTC_Deed_PROP013.pdf", "Water_Source_Cert.pdf"],
    available: true,
  },
  // ── BELAGAVI ─────────────────────────────────────────────────────────────────
  {
    id: "PROP-005",
    surveyNumber: "12/4B",
    district: "Belagavi",
    taluk: "Chikodi",
    hobli: "Sadalga",
    village: "Kognoli",
    ownerName: "Devendra Patil",
    ownerPhone: "+91 96112 44781",
    areaAcres: 3,
    areaGuntas: 0,
    propertyType: "Agricultural",
    valuation: 8500000,
    lat: 16.5512,
    lng: 74.4532,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "120, Sadalga Road, Kognoli, Chikodi Taluk, Belagavi, Karnataka 591201",
    internalNotes: "Approved for refinance. Customer wants to apply for refinance top-up.",
    documents: ["RTC_Deed_PROP005.pdf"],
    available: true,
  },
  {
    id: "PROP-014",
    surveyNumber: "78/3",
    district: "Belagavi",
    taluk: "Belagavi",
    hobli: "Belagavi Rural",
    village: "Kanagala",
    ownerName: "Shivakumar N. Patil",
    ownerPhone: "+91 98441 22180",
    areaAcres: 2,
    areaGuntas: 28,
    propertyType: "Agricultural",
    valuation: 6700000,
    lat: 15.8497,
    lng: 74.5082,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Kanagala, Belagavi Rural Hobli, Belagavi, Karnataka 590015",
    internalNotes: "Sugarcane plantation land. Loan secured against harvest revenue.",
    documents: ["RTC_Deed_PROP014.pdf", "Kisan_Credit_Card.pdf"],
    available: true,
  },
  {
    id: "PROP-015",
    surveyNumber: "200/A",
    district: "Belagavi",
    taluk: "Raibag",
    hobli: "Raibag Hobli",
    village: "Yalvigi",
    ownerName: "Annapurna Desai",
    ownerPhone: "+91 97415 66230",
    areaAcres: 8,
    areaGuntas: 12,
    propertyType: "Agricultural",
    valuation: 19200000,
    lat: 16.4888,
    lng: 74.7620,
    status: "Pending",
    assignedTo: "Unassigned",
    ownerAddress: "Yalvigi Village, Raibag Taluk, Belagavi, Karnataka 591317",
    internalNotes: "Large agricultural holding. Awaiting RTC update from Taluk office.",
    documents: ["Mutation_Application_PROP015.pdf"],
    available: false,
  },
  // ── DAKSHINA KANNADA / MANGALURU ──────────────────────────────────────────────
  {
    id: "PROP-006",
    surveyNumber: "301/A",
    district: "Mangaluru (Dakshina Kannada)",
    taluk: "Mangaluru",
    hobli: "Panambur",
    village: "Baikampady",
    ownerName: "Joseph D'Souza",
    ownerPhone: "+91 98860 77123",
    areaAcres: 0,
    areaGuntas: 18,
    propertyType: "Industrial",
    valuation: 32000000,
    lat: 12.9341,
    lng: 74.8315,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "8-A, Baikampady Industrial Area, Mangaluru, Karnataka 575011",
    internalNotes: "Industrial site. High valuation, verified under corporate loan schema.",
    documents: ["RTC_Deed_PROP006.pdf", "Industrial_Permit.pdf"],
    available: true,
  },
  {
    id: "PROP-007",
    surveyNumber: "77/9",
    district: "Mangaluru (Dakshina Kannada)",
    taluk: "Bantwal",
    hobli: "Vittal",
    village: "Kabaka",
    ownerName: "Saraswathi Shenoy",
    ownerPhone: "+91 94498 66251",
    areaAcres: 1,
    areaGuntas: 5,
    propertyType: "Agricultural",
    valuation: 6200000,
    lat: 12.7523,
    lng: 75.1234,
    status: "Disputed",
    assignedTo: "Unassigned",
    ownerAddress: "99, Vittal Hobli, Bantwal, Dakshina Kannada, Karnataka 574243",
    internalNotes: "Disputed boundary with neighboring plot 77/10. Legal hold active.",
    documents: ["Dispute_Notice.pdf"],
    available: false,
  },
  {
    id: "PROP-016",
    surveyNumber: "45/12",
    district: "Mangaluru (Dakshina Kannada)",
    taluk: "Puttur",
    hobli: "Vitla",
    village: "Shishila",
    ownerName: "Ramakrishna Bhat",
    ownerPhone: "+91 94486 78901",
    areaAcres: 2,
    areaGuntas: 22,
    propertyType: "Agricultural",
    valuation: 7400000,
    lat: 12.7652,
    lng: 75.1987,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "Shishila, Vitla Hobli, Puttur Taluk, DK, Karnataka 574203",
    internalNotes: "Areca nut and coconut plantation. Steady produce income confirmed.",
    documents: ["RTC_Deed_PROP016.pdf"],
    available: true,
  },
  // ── HUBLI-DHARWAD ─────────────────────────────────────────────────────────────
  {
    id: "PROP-008",
    surveyNumber: "109/2",
    district: "Hubli-Dharwad (Dharwad)",
    taluk: "Hubli",
    hobli: "Hubli Rural",
    village: "Gopankoppa",
    ownerName: "Girish Hublikar",
    ownerPhone: "+91 99805 12567",
    areaAcres: 0,
    areaGuntas: 35,
    propertyType: "Residential",
    valuation: 7800000,
    lat: 15.3725,
    lng: 75.1614,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Flat 202, Gopankoppa Rural, Hubli, Dharwad, Karnataka 580025",
    internalNotes: "Residential building under construction. Progress checked by executive.",
    documents: ["RTC_Deed_PROP008.pdf", "Building_Plan_Approval.pdf"],
    available: true,
  },
  {
    id: "PROP-009",
    surveyNumber: "56/3A",
    district: "Hubli-Dharwad (Dharwad)",
    taluk: "Dharwad",
    hobli: "Dharwad Hobli",
    village: "Hebballi",
    ownerName: "Mallikarjun Shinde",
    ownerPhone: "+91 96200 45890",
    areaAcres: 5,
    areaGuntas: 12,
    propertyType: "Agricultural",
    valuation: 14000000,
    lat: 15.4832,
    lng: 75.0312,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "4, Dharwad Hobli, Hebballi, Dharwad, Karnataka 580001",
    internalNotes: "Agricultural land verification done. Soil testing certificate uploaded.",
    documents: ["RTC_Deed_PROP009.pdf"],
    available: true,
  },
  {
    id: "PROP-017",
    surveyNumber: "33/5",
    district: "Hubli-Dharwad (Dharwad)",
    taluk: "Hubli",
    hobli: "Hubli City",
    village: "Vidyanagar",
    ownerName: "Uday Kulkarni",
    ownerPhone: "+91 97312 90022",
    areaAcres: 0,
    areaGuntas: 10,
    propertyType: "Commercial",
    valuation: 15500000,
    lat: 15.3647,
    lng: 75.1240,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "1st Cross, Vidyanagar, Hubli, Dharwad, Karnataka 580031",
    internalNotes: "Commercial showroom site. Prime location near NH-48.",
    documents: ["RTC_Deed_PROP017.pdf", "HUDCO_Plan_Approval.pdf"],
    available: true,
  },
  // ── KALABURAGI ────────────────────────────────────────────────────────────────
  {
    id: "PROP-018",
    surveyNumber: "88/5B",
    district: "Kalaburagi",
    taluk: "Kalaburagi",
    hobli: "Jewargi",
    village: "Chincholi",
    ownerName: "Basappa Kalyanakar",
    ownerPhone: "+91 96632 11200",
    areaAcres: 10,
    areaGuntas: 0,
    propertyType: "Agricultural",
    valuation: 11000000,
    lat: 17.4638,
    lng: 76.8212,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "Chincholi Village, Kalaburagi Taluk, Karnataka 585307",
    internalNotes: "Dryland farming. Bore well installed 2024. Yield records available.",
    documents: ["RTC_Deed_PROP018.pdf"],
    available: true,
  },
  // ── SHIVAMOGGA ────────────────────────────────────────────────────────────────
  {
    id: "PROP-019",
    surveyNumber: "65/2",
    district: "Shivamogga",
    taluk: "Shivamogga",
    hobli: "Shivamogga",
    village: "Doddapete",
    ownerName: "Hemavathi S. Naik",
    ownerPhone: "+91 96868 55433",
    areaAcres: 0,
    areaGuntas: 20,
    propertyType: "Residential",
    valuation: 6900000,
    lat: 13.9299,
    lng: 75.5681,
    status: "Verified",
    assignedTo: "Bibi Ayesha",
    ownerAddress: "Doddapete Ward, Shivamogga City, Karnataka 577201",
    internalNotes: "Site plan approved by SUDA (Shivamogga Urban Development Authority).",
    documents: ["RTC_Deed_PROP019.pdf", "SUDA_Approval.pdf"],
    available: true,
  },
  // ── TUMAKURU ──────────────────────────────────────────────────────────────────
  {
    id: "PROP-020",
    surveyNumber: "121/6C",
    district: "Tumakuru",
    taluk: "Tiptur",
    hobli: "Turuvekere",
    village: "Aralaguppe",
    ownerName: "Ravi Subramanyam",
    ownerPhone: "+91 99001 87643",
    areaAcres: 7,
    areaGuntas: 4,
    propertyType: "Agricultural",
    valuation: 13500000,
    lat: 13.2595,
    lng: 76.4712,
    status: "Verified",
    assignedTo: "R H Adhoni",
    ownerAddress: "Aralaguppe, Turuvekere Hobli, Tiptur Taluk, Tumakuru, Karnataka 572228",
    internalNotes: "Coconut grove with drip irrigation. Clean title. Ready for agri-loan.",
    documents: ["RTC_Deed_PROP020.pdf", "Kisan_Vitran_Receipt.pdf"],
    available: true,
  },
];
