/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as InsuranceIndexRouteImport } from './routes/insurance.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LoansSlugRouteImport } from './routes/loans.$slug'
import { Route as InsuranceSlugRouteImport } from './routes/insurance.$slug'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoansRoute,
} as any)
const InsuranceIndexRoute = InsuranceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsuranceRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LoansSlugRoute = LoansSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LoansRoute,
} as any)
const InsuranceSlugRoute = InsuranceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsuranceRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/insurance': typeof InsuranceRouteWithChildren
  '/loans': typeof LoansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/admin': typeof AdminIndexRoute
  '/insurance': typeof InsuranceIndexRoute
  '/loans': typeof LoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/insurance': typeof InsuranceRouteWithChildren
  '/loans': typeof LoansRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/insurance'
    | '/loans'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/sms'
    | '/insurance/$slug'
    | '/loans/$slug'
    | '/admin/'
    | '/insurance/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/sms'
    | '/insurance/$slug'
    | '/loans/$slug'
    | '/admin'
    | '/insurance'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/insurance'
    | '/loans'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/sms'
    | '/insurance/$slug'
    | '/loans/$slug'
    | '/admin/'
    | '/insurance/'
    | '/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InsuranceRoute: typeof InsuranceRouteWithChildren
  LoansRoute: typeof LoansRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof LoansRoute
    }
    '/insurance/': {
      id: '/insurance/'
      path: '/'
      fullPath: '/insurance/'
      preLoaderRoute: typeof InsuranceIndexRouteImport
      parentRoute: typeof InsuranceRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loans/$slug': {
      id: '/loans/$slug'
      path: '/$slug'
      fullPath: '/loans/$slug'
      preLoaderRoute: typeof LoansSlugRouteImport
      parentRoute: typeof LoansRoute
    }
    '/insurance/$slug': {
      id: '/insurance/$slug'
      path: '/$slug'
      fullPath: '/insurance/$slug'
      preLoaderRoute: typeof InsuranceSlugRouteImport
      parentRoute: typeof InsuranceRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InsuranceRouteChildren {
  InsuranceSlugRoute: typeof InsuranceSlugRoute
  InsuranceIndexRoute: typeof InsuranceIndexRoute
}

const InsuranceRouteChildren: InsuranceRouteChildren = {
  InsuranceSlugRoute: InsuranceSlugRoute,
  InsuranceIndexRoute: InsuranceIndexRoute,
}

const InsuranceRouteWithChildren = InsuranceRoute._addFileChildren(
  InsuranceRouteChildren,
)

interface LoansRouteChildren {
  LoansSlugRoute: typeof LoansSlugRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

const LoansRouteChildren: LoansRouteChildren = {
  LoansSlugRoute: LoansSlugRoute,
  LoansIndexRoute: LoansIndexRoute,
}

const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InsuranceRoute: InsuranceRouteWithChildren,
  LoansRoute: LoansRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
